### ISSUE TITLE
Debian单词读音音标错误

### ISSUE THREAD

**Issue by frankli0324** [guanpengchn/awesome-pronunciation#4]
**Bug content**
语音链接读音正确，但音标错误(以至于我一度认为我读错了)
https://www.debian.org/intro/about 中写道：

> Since many people have asked, Debian is pronounced /ˈde.bi.ən/. It comes from the names of the creator of Debian, Ian Murdock, and his wife, Debra.

有可能的话请对其它条目进行复查

**Comment by guanpengchn** [comment]
非常感谢建议，根据您提供的参考资料我已经修改了[Debian](https://guanpengchn.github.io/awesome-pronunciation/content/D.html)的音标，我会对其他条目进行复查
